/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	armadasv1alpha1 "github.com/chmouel/armadas/pkg/apis/armadas/v1alpha1"
	versioned "github.com/chmouel/armadas/pkg/client/clientset/versioned"
	internalinterfaces "github.com/chmouel/armadas/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/chmouel/armadas/pkg/client/listers/armadas/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FireInformer provides access to a shared informer and lister for
// Fires.
type FireInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.FireLister
}

type fireInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFireInformer constructs a new informer for Fire type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFireInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFireInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFireInformer constructs a new informer for Fire type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFireInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GithubV1alpha1().Fires(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GithubV1alpha1().Fires(namespace).Watch(context.TODO(), options)
			},
		},
		&armadasv1alpha1.Fire{},
		resyncPeriod,
		indexers,
	)
}

func (f *fireInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFireInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *fireInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&armadasv1alpha1.Fire{}, f.defaultInformer)
}

func (f *fireInformer) Lister() v1alpha1.FireLister {
	return v1alpha1.NewFireLister(f.Informer().GetIndexer())
}
