/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/chmouel/armadas/pkg/apis/armadas/v1alpha1"
	scheme "github.com/chmouel/armadas/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArmadasGetter has a method to return a ArmadaInterface.
// A group's client should implement this interface.
type ArmadasGetter interface {
	Armadas(namespace string) ArmadaInterface
}

// ArmadaInterface has methods to work with Armada resources.
type ArmadaInterface interface {
	Create(ctx context.Context, armada *v1alpha1.Armada, opts v1.CreateOptions) (*v1alpha1.Armada, error)
	Update(ctx context.Context, armada *v1alpha1.Armada, opts v1.UpdateOptions) (*v1alpha1.Armada, error)
	UpdateStatus(ctx context.Context, armada *v1alpha1.Armada, opts v1.UpdateOptions) (*v1alpha1.Armada, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Armada, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ArmadaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Armada, err error)
	ArmadaExpansion
}

// armadas implements ArmadaInterface
type armadas struct {
	client rest.Interface
	ns     string
}

// newArmadas returns a Armadas
func newArmadas(c *GithubV1alpha1Client, namespace string) *armadas {
	return &armadas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the armada, and returns the corresponding armada object, and an error if there is any.
func (c *armadas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Armada, err error) {
	result = &v1alpha1.Armada{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armadas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Armadas that match those selectors.
func (c *armadas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ArmadaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ArmadaList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armadas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested armadas.
func (c *armadas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("armadas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a armada and creates it.  Returns the server's representation of the armada, and an error, if there is any.
func (c *armadas) Create(ctx context.Context, armada *v1alpha1.Armada, opts v1.CreateOptions) (result *v1alpha1.Armada, err error) {
	result = &v1alpha1.Armada{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("armadas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armada).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a armada and updates it. Returns the server's representation of the armada, and an error, if there is any.
func (c *armadas) Update(ctx context.Context, armada *v1alpha1.Armada, opts v1.UpdateOptions) (result *v1alpha1.Armada, err error) {
	result = &v1alpha1.Armada{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armadas").
		Name(armada.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armada).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *armadas) UpdateStatus(ctx context.Context, armada *v1alpha1.Armada, opts v1.UpdateOptions) (result *v1alpha1.Armada, err error) {
	result = &v1alpha1.Armada{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armadas").
		Name(armada.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armada).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the armada and deletes it. Returns an error if one occurs.
func (c *armadas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armadas").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *armadas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armadas").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched armada.
func (c *armadas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Armada, err error) {
	result = &v1alpha1.Armada{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("armadas").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
